import "server-only";

// Guides complets (repris de la fonction Supabase « inscription », passés au vouvoiement).
// Servis uniquement côté serveur : contenu complet pour les acheteurs, deux chapitres sinon.
const ch = (n: string, titre: string, corps: string) => `<section class="eb-ch"><span class="eb-n">${n}</span><h4>${titre}</h4>${corps}</section>`;
const ul = (cls: string, items: string[]) => `<ul class="${cls}">${items.map((i) => `<li>${i}</li>`).join("")}</ul>`;
const ol = (items: string[]) => `<ol class="eb-q">${items.map((i) => `<li>${i}</li>`).join("")}</ol>`;
const cover = (tag: string, titre: string, intro: string, sommaire: string) => `<header class="eb-cover"><span class="eb-tag">${tag}</span><h3>${titre}</h3><p>${intro}</p><p class="eb-small">${sommaire}</p></header>`;
const calc = (rows: [string, string, string?][], tot: [string, string]) => `<div class="eb-calc">${rows.map(([a, b, c]) => `<div class="${c ?? ""}"><span>${a}</span><b>${b}</b></div>`).join("")}<div class="t"><span>${tot[0]}</span><b>${tot[1]}</b></div></div>`;
const sc = (label: string, texte: string) => `<div class="eb-sc"><span>${label}</span><p>${texte}</p></div>`;
const bx = (titre: string, corps: string, warn = false) => `<div class="eb-bx${warn ? " w" : ""}"><b>${titre}</b>${corps}</div>`;
const tab = (tete: string[], lignes: string[][], noCol = -1) => `<div class="eb-tw"><table class="eb-t"><tr>${tete.map((t) => `<th>${t}</th>`).join("")}</tr>${lignes.map((l) => `<tr>${l.map((c, i) => `<td${i === noCol ? ' class="no"' : ""}>${i === 0 ? `<b>${c}</b>` : c}</td>`).join("")}</tr>`).join("")}</table></div>`;

// ------------------------------------------------------------------ blocs communs
const CITADINES: string[][] = [
  ["Renault Clio III / IV", "1.2 16V 75, 1.5 dCi 75/85/90", "AL4, EDC, TCe 120"],
  ["Toyota Yaris II / III", "1.0 et 1.33 VVT-i, 1.4 D-4D", "Robotisée MMT"],
  ["Aygo / C1 / 107", "1.0 68 ch", "Robotisée"],
  ["Honda Jazz II / III", "1.2 et 1.4 i-VTEC manuelle", "i-Shift robotisée"],
  ["Suzuki Swift", "1.2 VVT 94 ch", "Rien de notable"],
  ["Mazda 2", "1.3 et 1.5 essence", "Sans suivi d'entretien"],
  ["Dacia Sandero I / II", "1.2 16V, 1.5 dCi, 0.9 TCe", "Easy-R robotisée"],
  ["Peugeot 207", "1.4 HDi 70, 1.6 HDi 90", "1.6 THP, VTi, AL4"],
  ["Peugeot 208 diesel", "HDi, BlueHDi", "1.2 PureTech, ETG"],
  ["Citroën C3 II", "1.4 HDi, 1.6 HDi / BlueHDi", "1.2 PureTech, ETG"],
  ["Ford Fiesta VI", "1.25 Duratec, 1.4 TDCi", "1.0 EcoBoost, Powershift"],
  ["Hyundai i20 / Kia Rio", "1.2 / 1.25, 1.4 CRDi", "Sans carnet"],
  ["Hyundai i10 / Kia Picanto", "1.0 et 1.2 essence", "Auto 4 rapports usée"],
  ["Toyota Auris", "1.33 / 1.6 VVT-i, 1.4 D-4D, hybride", "2.0 / 2.2 D-4D"],
  ["Volkswagen Polo V", "1.6 TDI, 1.4 MPI", "DSG7, premiers 1.2 TSI"],
  ["Renault Twingo II", "1.2 16V 75", "Quickshift robotisée"],
  ["Škoda Fabia II / III", "1.6 TDI, 1.0 MPI", "DSG, 1.2 HTP sans preuve"],
];
const tableCitadines = () => tab(["Modèle", "À prendre", "À éviter"], CITADINES, 2);
const PANNES_L: string[][] = [
  ["Plaquettes + disques avant", "150 – 300 €"], ["2 pneus", "140 – 260 €"], ["Batterie", "100 – 200 €"],
  ["Vidange + filtres", "80 – 150 €"], ["Kit distribution + pompe à eau", "350 – 700 €"], ["Embrayage", "450 – 800 €"],
  ["Amortisseurs avant", "250 – 450 €"], ["Vanne EGR", "250 – 600 €"], ["Rénovation des 2 optiques", "40 – 120 €"],
  ["Retouche rayure / smart repair", "80 – 200 € par élément"], ["Pare-brise", "0 – 400 € (souvent pris par l'assurance bris de glace)"],
  ["Recharge clim", "70 – 120 €"],
];
const PANNES = `${tab(["Intervention (citadine)", "Fourchette indicative"], PANNES_L)}<p class="eb-small">Pièces et main-d'œuvre en garage indépendant. Les prix varient selon le modèle et la région. Sans diagnostic, prévoir le haut de la fourchette.</p>`;
const MOTEURS = ul("eb-no", ["<b>1.2 PureTech</b> (Peugeot, Citroën, DS, Opel) : courroie de distribution qui baigne dans l'huile, consommation d'huile", "<b>1.6 THP / VTi</b> (Peugeot, Citroën, Mini) : chaîne de distribution", "<b>1.0 EcoBoost</b> (Ford) : circuit de refroidissement", "<b>TCe 115 / 120</b> (Renault, Dacia, Nissan) : consommation d'huile", "<b>Boîtes robotisées et double embrayage</b> : EDC, DSG, Powershift, ETG, MMT, Easy-R, Quickshift, AL4"]);
const ESSAI = ul("eb-ok", ["<b>Moteur froid</b> : posez la main sur le capot en arrivant. S'il est chaud, le vendeur a peut-être caché un démarrage difficile", "<b>Au contact</b> : tous les voyants s'allument puis s'éteignent. Un voyant qui ne s'allume jamais peut avoir été débranché", "<b>Démarrage</b> : pas de claquement, pas de fumée bleue (huile) ni blanche épaisse et persistante (liquide de refroidissement)", "<b>Embrayage</b> : s'il accroche tout en haut de la course, il est usé", "<b>Vitesses</b> : passent sans craquement, y compris la marche arrière", "<b>Freinage</b> : droit, sans vibration dans le volant ni la pédale", "<b>Direction</b> : la voiture ne tire pas d'un côté, pas de bruit en braquant à fond", "<b>Clim</b> : elle fait du froid en moins d'une minute", "<b>Après l'essai</b> : regardez sous la voiture (taches d'huile) et sous le bouchon d'huile (dépôt blanchâtre = mauvais signe)"]);
const PAPIERS = ul("eb-ok", ["Carte grise barrée, avec la mention « Vendu le … à … h » et la signature du vendeur", "Certificat de cession (cerfa 15776) en 2 exemplaires, signé par les deux", "Code de cession remis par le vendeur après sa déclaration en ligne sur le site de l'ANTS", "Certificat de situation administrative de moins de 15 jours (pas de gage, pas d'opposition)", "PV de contrôle technique de moins de 6 mois si la voiture a plus de 4 ans", "Nom sur la carte grise = pièce d'identité de la personne en face. VIN de la carte grise = VIN gravé sur la voiture (pare-brise et montant de porte)"]);
const PAIEMENT = ul("eb-no", ["Jamais d'argent avant d'avoir vu la voiture et les papiers", "Pas de vendeur « à l'étranger » qui propose une livraison", "Pas d'acompte par mandat cash, coupon ou crypto", "Chèque de banque : appelez la banque émettrice avec un numéro que vous avez trouvé vous-même, pas celui écrit sur le chèque", "Le plus sûr : un virement instantané, fait ensemble, reçu sur le compte avant de remettre les clés"]);
const CLIO = ul("eb-ok", ["Version société 2 places : <b>− 21 %</b>", "Break : <b>− 2 %</b>", "Finition haute : <b>+ 5 %</b>", "Chaque année et chaque tranche de 10 000 km en plus font baisser la cote"]);

// ================================================================== 1. Débutant
function guideDebutant(prenom: string) {
  return `<div class="eb">${cover("Guide complet", "Votre première revente, étape par étape", `${prenom}, ce guide vous montre comment faire votre première revente de voiture sans perdre d'argent, puis viser 500 à 1 000 € par mois. Tout est dans l'ordre : le cadre légal, comment démarrer sans argent, choisir, trouver, estimer, acheter, préparer, vendre.`, "16 chapitres · environ 35 minutes de lecture · imprimable en PDF")}
${ch("Chapitre 1", "Les vrais chiffres, avant de rêver", `<p>Sur une citadine bien achetée, il reste en général <b>400 à 800 € nets</b> une fois tout payé. Pas 3 000 €. Voici un exemple réaliste :</p>${calc([["Achat négocié", "5 000 €"], ["Carte grise à votre nom (selon région)", "− 200 €", "m"], ["2 pneus + parallélisme", "− 220 €", "m"], ["Préparation, nettoyage", "− 60 €", "m"], ["CT de moins de 6 mois", "− 80 €", "m"], ["Trajets, annonces", "− 70 €", "m"], ["Revente", "6 300 €"]], ["Bénéfice avant cotisations", "670 €"])}
<p>Ce qui fait la différence entre un bon et un mauvais deal :</p>${ul("eb-ok", ["<b>Le prix d'achat</b> : c'est là que se fait 80 % de votre marge", "<b>La rotation</b> : une voiture qui reste 2 mois vous coûte du temps, de l'assurance et de la patience", "<b>Les imprévus</b> : gardez toujours 15 % du prix d'achat de côté pour une mauvaise surprise"])}
<p><b>500 à 1 000 € par mois</b>, c'est une à deux voitures bien achetées et bien revendues. Atteignable, mais c'est un vrai travail : comptez 10 à 15 heures par voiture au début.</p>`)}
${ch("Chapitre 2", "Le cadre légal, dès le départ", `<p>Vendre votre propre voiture de temps en temps, c'est une vente entre particuliers. <b>Acheter pour revendre de façon régulière, c'est une activité commerciale.</b> Elle doit être déclarée, sinon vous risquez un redressement et une amende pour travail dissimulé.</p>
${ul("eb-ok", ["<b>Micro-entreprise</b> : la plus simple à créer, gratuite, en ligne. Pour l'achat-revente, les cotisations sont d'environ <b>12,3 % du prix de vente</b>, pas du bénéfice", "<b>Entreprise au réel ou société</b> : vous payez sur le bénéfice réel, plus adapté quand vous faites plusieurs voitures par mois. Demandez à un comptable", "<b>Registre de police</b> : tout revendeur d'objets d'occasion doit tenir un registre des achats et faire une déclaration en préfecture", "<b>Habilitation SIV</b> : une fois professionnel, elle vous permet de déclarer vos achats sans refaire de carte grise à votre nom à chaque voiture"])}
${bx("Le piège de la micro-entreprise", `<p>Sur la voiture du chapitre 1 revendue 6 300 €, les cotisations en micro-entreprise sont d'environ 775 €. Votre bénéfice de 670 € devient négatif. En micro, l'achat-revente ne marche que si votre marge dépasse nettement 12 % du prix de vente, ou si vous commencez par le mandat (chapitre 3), où vous ne payez des cotisations que sur votre commission.</p>`, true)}
<p class="eb-small">Taux et règles en vigueur en 2026 en France, à vérifier sur le site de l'Urssaf ou avec votre CCI avant de vous lancer. Ce guide n'est pas un conseil juridique ou comptable.</p>`)}
${ch("Chapitre 3", "Commencer sans argent : le mandat de vente", `<p>Vous n'avez pas besoin d'acheter une voiture pour gagner votre première commission. Beaucoup de particuliers n'ont ni le temps ni l'envie de vendre leur voiture : photos ratées, annonce vide, appels de curieux, rendez-vous annulés. <b>Vous vendez leur voiture pour eux, contre une commission.</b></p>
${ul("eb-ok", ["Vous faites les photos, l'annonce, vous répondez aux appels et vous organisez les visites", "L'acheteur paie <b>directement le vendeur</b> : vous ne touchez jamais l'argent de la voiture", "Vous êtes payé à la vente : un montant fixe (200 à 400 € sur une citadine) ou un pourcentage", "Aucun argent immobilisé, aucun risque mécanique pour vous"])}
<p><b>Ce que doit contenir votre mandat écrit</b> (une page suffit) :</p>${ul("eb-ok", ["Identité du vendeur et la vôtre", "Voiture : immatriculation, VIN, kilométrage", "Prix de vente minimum accepté par le vendeur", "Votre commission, en euros, et quand elle est due (à la signature de la cession)", "Durée : 15 à 30 jours", "Exclusif ou non, et qui fait les visites", "Date et deux signatures"])}
${sc("Message au vendeur", `Bonjour, je vends des voitures pour les particuliers qui n'ont pas le temps de s'en occuper. Je m'occupe des photos, de l'annonce, des appels et des visites. Vous ne payez rien avant la vente, et l'acheteur vous paie directement. Est-ce que ça vous intéresserait qu'on en parle 5 minutes ?`)}
<p><b>Qui viser :</b> annonces en ligne depuis plus de 3 semaines, photos floues ou prises de nuit, texte de 2 lignes, prix cohérent avec le marché. Un vendeur qui baisse son prix pour la deuxième fois est souvent prêt à se faire aider.</p>
<p class="eb-small">Toucher des commissions de façon régulière est aussi une activité à déclarer. En micro-entreprise, une commission est une prestation de service : environ 21 % de cotisations, calculées sur la commission seulement.</p>`)}
${ch("Chapitre 4", "Quelles voitures viser", `<p>Achetez ce que les autres cherchent, pas ce qui vous plaît. Pour débuter, visez des citadines courantes : beaucoup d'acheteurs, pièces pas chères, entretien connu.</p>
${ul("eb-ok", ["<b>Prix</b> : 3 000 à 7 000 €, là où il y a le plus d'acheteurs", "<b>Âge</b> : 6 à 12 ans", "<b>Kilométrage</b> : 80 000 à 160 000 km. Au-delà de 180 000 km, ça se vend, mais lentement et moins cher", "<b>Boîte manuelle</b>, essence ou diesel simple", "<b>Carnet ou factures</b> : une voiture avec son historique se vend plus vite et plus cher"])}
${tableCitadines()}<p>À éviter au début : premium (pièces chères), électriques et hybrides rechargeables (batterie impossible à juger), boîtes automatiques, modèles rares, utilitaires, voitures de moins de 3 ans.</p>`)}
${ch("Chapitre 5", "Les moteurs et les boîtes à fuir", `${MOTEURS}<p>Un de ces moteurs avec toutes ses factures peut passer. Le même sans aucune preuve d'entretien : vous passez votre tour, même si le prix a l'air bon. C'est souvent pour ça qu'il a l'air bon.</p>
${bx("Les défauts éliminatoires, quel que soit le prix", ul("eb-no", ["Fumée blanche épaisse, mayonnaise sous le bouchon d'huile, surchauffe : joint de culasse", "Voyant moteur ou airbag allumé sans diagnostic", "Kilométrage incohérent avec les CT ou les factures", "Voiture gagée, papiers manquants, vendeur qui n'est pas sur la carte grise", "Traces de choc sur les longerons, soudures, peinture différente sur plusieurs éléments"]), true)}`)}
${ch("Chapitre 6", "Trouver les bonnes annonces avant les autres", `<p>Les bonnes affaires partent en quelques heures. Votre avantage, c'est la vitesse.</p>
${ul("eb-ok", ["<b>Créez des alertes</b> sur Leboncoin, La Centrale et Facebook Marketplace : modèle, moteur, prix max, kilométrage max, particuliers uniquement", "<b>Élargissez la zone</b> : hors des grandes villes, les prix sont souvent plus bas. Vous revendez ensuite là où il y a plus d'acheteurs", "<b>Regardez tôt le matin et le soir</b> : beaucoup de particuliers publient après le travail", "<b>Répondez en moins de 15 minutes</b> à une annonce intéressante"])}
<p><b>Les signaux d'une opportunité :</b></p>${ul("eb-ok", ["Vendeur pressé : « déménagement », « départ à l'étranger », « achat d'une autre voiture », « urgent »", "Annonce mal faite : 2 photos sombres, peu de texte. Moins de concurrence, et la voiture peut être revalorisée juste avec de bonnes photos", "Petit défaut qui fait peur : « clim à recharger », « rayure », « pneus à changer ». Chiffrable, et le vendeur le surévalue souvent", "Prix un peu au-dessus du marché depuis longtemps : le vendeur est prêt à discuter"])}`)}
${ch("Chapitre 7", "Estimer le vrai prix de revente", `<p>Le prix de revente, c'est le prix auquel <b>votre</b> voiture partira en 2 à 3 semaines. Pas le prix de l'annonce la plus chère.</p>
${ol(["Cherchez au moins <b>20 annonces</b> : même modèle et même moteur, année à ± 1 an, kilométrage à ± 30 000 km", "Retirez les voitures accidentées, pour pièces, les doublons et les prix délirants", "Classez-les par prix et regardez le milieu du tableau : c'est la cote affichée", "Retirez 5 à 8 % : les voitures se vendent en général un peu sous le prix affiché", "Ajustez : finition, entretien, état, contrôle technique, couleur"])}
<p>Écarts mesurés sur 189 annonces de Clio IV diesel :</p>${CLIO}
<p>Gardez vos recherches dans un tableau simple. Après 3 ou 4 voitures du même modèle, vous connaîtrez les prix par cœur.</p>`)}
${ch("Chapitre 8", "Calculer votre prix maximum avant d'appeler", `<p class="eb-formula">Revente réaliste − travaux − frais − votre marge = <b>votre prix max</b></p>
${calc([["Revente réaliste", "6 300 €"], ["Travaux prévus", "− 400 €", "m"], ["Frais (carte grise, CT, trajets)", "− 350 €", "m"], ["Marge voulue", "− 700 €", "m"]], ["Prix max", "4 850 €"])}
<p>Au-dessus, vous passez à l'annonce suivante, même si la voiture vous plaît. <b>Votre marge se fait le jour où vous achetez.</b></p>
<p>Votre première offre : environ 6 à 8 % sous votre prix max, arrondie. Ici, <b>4 500 €</b>. Vous avez de la place pour discuter sans dépasser votre limite.</p>`)}
${ch("Chapitre 9", "Le premier contact", `${sc("Premier message", `Bonjour, votre [modèle] m'intéresse. Elle est toujours disponible ? J'ai quelques questions avant de venir la voir.`)}
<p>Puis, par téléphone de préférence (vous entendez les hésitations) :</p>${ol(["Depuis quand vous l'avez ? Pourquoi vous la vendez ?", "Vous avez les factures d'entretien ? La distribution a été faite à quel kilométrage ?", "Le CT a moins de 6 mois ? Il y a une contre-visite ?", "Un voyant allumé, un bruit, une fuite, quelque chose à prévoir ?", "Pouvez-vous m'envoyer le rapport HistoVec ?"])}
<p><b>HistoVec</b> est gratuit, sur le site du gouvernement : le vendeur le génère en 2 minutes. Vous y voyez le nombre de propriétaires, les kilométrages relevés aux CT, les sinistres déclarés et les gages. Un vendeur qui refuse de l'envoyer : vous passez.</p>
${bx("Drapeaux rouges au téléphone", ul("eb-no", ["Il ne sait rien de l'entretien ni du kilométrage de la distribution", "Il refuse que vous veniez avec un mécanicien", "Il veut un acompte avant la visite", "Le nom qu'il donne n'est pas celui de la carte grise"]), true)}`)}
${ch("Chapitre 10", "L'inspection et l'essai", `<p><b>Avant de rouler, faites le tour de la voiture (10 minutes) :</b></p>${ul("eb-ok", ["Écarts entre les panneaux réguliers, même teinte partout (regardez en biais, à la lumière du jour)", "Pneus : même marque par essieu, usure égale. Une usure d'un seul côté = géométrie faussée, parfois après un choc", "Phares, pare-brise, jantes, bas de caisse", "Intérieur : volant, pommeau et siège conducteur cohérents avec le kilométrage", "Coffre : roue de secours, cric, pas d'humidité sous le tapis", "Moteur : niveau et couleur d'huile, liquide de refroidissement propre, pas de fuite"])}
<p><b>Puis l'essai de 10 minutes :</b></p>${ESSAI}
${bx("L'outil à 20 €", `<p>Une valise OBD Bluetooth et une appli gratuite lisent les codes défauts, même quand aucun voyant n'est allumé. Branchez-la avant l'essai. Des défauts effacés récemment, c'est un signal à creuser.</p>`)}
<p>Au moindre doute, proposez un passage chez un garagiste avant l'achat (50 à 100 €). Si le vendeur refuse, vous avez votre réponse.</p>`)}
${ch("Chapitre 11", "Négocier sans être désagréable", `<p>Vous ne négociez pas sur une impression, vous négociez <b>avec des défauts chiffrés</b>. Chaque défaut vu pendant l'essai ou sur le PV de CT devient une ligne de calcul.</p>${PANNES}
${sc("Présenter votre offre", `La voiture me plaît. Par contre il y a les deux pneus avant à changer et les plaquettes, ça fait environ 450 €, et le CT signale un défaut à reprendre. Je peux vous proposer 4 500 €, et je peux faire le virement aujourd'hui.`)}
${sc("S'il refuse", `Je comprends. Je ne peux pas monter beaucoup, mon maximum c'est 4 800 €. Si ça vous va, on fait les papiers maintenant.`)}
${sc("Sortie propre", `Pas de souci, je comprends que vous en attendiez plus. Je vous laisse mon numéro : si vous changez d'avis dans les jours qui viennent, appelez-moi.`)}
<p>Après votre offre, <b>taisez-vous</b>. Le premier qui parle perd souvent. Et notez chaque vendeur que vous quittez : beaucoup rappellent 5 à 10 jours plus tard.</p>`)}
${ch("Chapitre 12", "Payer et récupérer les bons papiers", `${PAPIERS}${PAIEMENT}
<p><b>Après l'achat :</b> le vendeur déclare la cession en ligne sous 15 jours. Vous avez <b>1 mois</b> pour mettre la carte grise à votre nom, et vous devez assurer la voiture avant de rouler. Une fois professionnel habilité, vous faites une déclaration d'achat à la place : pas de carte grise à payer à chaque voiture.</p>`)}
${ch("Chapitre 13", "Préparer la voiture : ce qui rapporte et ce qui ne rapporte pas", `${ul("eb-ok", ["<b>Nettoyage intérieur et extérieur complet</b> : 30 à 60 € en produits, ou 80 à 150 € chez un pro. Le meilleur rapport gain/effort", "<b>Rénovation des phares jaunis</b> : 20 € de kit, la voiture paraît plus jeune", "<b>Pneus</b> : l'acheteur les voit tout de suite. Des pneus lisses font baisser l'offre bien plus que leur prix", "<b>Vidange et filtres</b> avec facture : rassure l'acheteur", "<b>CT de moins de 6 mois</b> : obligatoire pour vendre à un particulier"])}
${ul("eb-no", ["Grosse carrosserie ou peinture complète : rarement rentable", "Accessoires, jantes, autoradio : ne se revalorisent pas", "Réparations mécaniques lourdes sans devis : c'est là qu'on perd de l'argent"])}
<p>Règle simple : chaque euro dépensé doit en rapporter au moins deux à la revente, ou accélérer la vente.</p>`)}
${ch("Chapitre 14", "Les photos et l'annonce qui vendent", `<p><b>Photos</b> : lumière du jour sans soleil direct, fond dégagé, voiture propre, au moins 20 photos.</p>${ul("eb-ok", ["3/4 avant, 3/4 arrière, les deux profils, face, arrière", "Tableau de bord moteur allumé, sans voyant, avec le kilométrage lisible", "Sièges avant et arrière, volant, coffre, moteur", "Pneus, jantes, et les défauts éventuels en gros plan", "Carnet et factures (sans les données personnelles)"])}
<p><b>L'annonce</b> : titre clair, puis les informations que l'acheteur cherche, dans cet ordre.</p>
${sc("Modèle d'annonce", `Renault Clio IV 1.5 dCi 90 Zen — 2016 — 128 000 km<br><br>Deuxième main, carnet d'entretien suivi, factures disponibles. Distribution faite à 120 000 km. CT de moins de 6 mois, aucune contre-visite. Pneus avant neufs, vidange faite. Clim, régulateur, GPS, Bluetooth.<br><br>Défaut : petite rayure sur le pare-chocs arrière (voir photo).<br><br>Visible à [ville]. Essai possible. Paiement par virement instantané ou chèque de banque vérifié.`)}
<p>Mentionner un petit défaut vous-même rassure. Mettez un prix légèrement au-dessus de votre prix de vente visé (+ 3 à 5 %) pour garder de la place à la négociation.</p>`)}
${ch("Chapitre 15", "Vendre : appels, visites, paiement, papiers", `${ul("eb-ok", ["Répondez vite et poliment, même aux questions déjà dans l'annonce", "Donnez rendez-vous dans un lieu public ou devant chez vous, de jour", "Vérifiez le permis de l'acheteur avant l'essai, et restez dans la voiture", "Ne remettez jamais les clés ni la carte grise avant d'avoir reçu l'argent sur votre compte"])}
<p><b>Les papiers que vous devez remettre :</b> carte grise barrée et signée, certificat de cession en 2 exemplaires, certificat de situation administrative de moins de 15 jours, PV de CT de moins de 6 mois. Puis vous déclarez la cession sur le site de l'ANTS dans les 15 jours et vous donnez le code de cession à l'acheteur.</p>
${bx("Après la vente", `<p>Résiliez l'assurance de la voiture, gardez une copie de tous les documents, et notez la vente dans votre registre. Si vous vendez en tant que professionnel, vous devez une garantie légale de conformité à l'acheteur : décrivez honnêtement l'état de la voiture par écrit.</p>`)}`)}
${ch("Chapitre 16", "Votre plan sur 30 jours", `${ul("eb-ok", ["<b>Jours 1 à 3</b> : choisissez 2 modèles dans le tableau du chapitre 4, créez vos alertes, commencez votre tableau de prix", "<b>Jours 4 à 10</b> : estimez 30 annonces sans acheter. Contactez 5 vendeurs pour un mandat (chapitre 3)", "<b>Jours 11 à 20</b> : décrochez votre premier mandat, faites les photos et l'annonce, organisez les visites", "<b>Jours 21 à 30</b> : vendez votre première voiture en mandat. Si vous avez le budget et une vraie affaire à moins de votre prix max, faites votre premier achat"])}
<p><b>Les 5 erreurs de débutant :</b></p>${ul("eb-no", ["Acheter une voiture qui vous plaît au lieu d'une voiture qui se vend", "Dépasser son prix max « parce qu'elle est vraiment bien »", "Oublier les frais et les cotisations dans son calcul", "Acheter sans HistoVec, sans essai ou sans CT", "Enchaîner les achats avant d'avoir vendu la première"])}`)}
<footer class="eb-end"><h4>Gardez ce guide sous la main</h4><p>Relisez les chapitres 8 à 12 avant chaque achat. Et pour chaque annonce, l'espace Benef calcule votre prix maximum, votre marge et votre offre en quelques secondes.</p></footer></div>`;
}

// ================================================================== 2. Marchands (vous)
function guideTri(prenom: string) {
  return `<div class="eb">${cover("Guide marchands", "Trier 40 annonces en 10 minutes", `${prenom}, voici la méthode complète que suit Utopicar, du paramétrage de vos recherches jusqu'au suivi de votre stock : passer de 40 annonces à 3 appels utiles, et de 3 appels à un achat rentable.`, "12 chapitres · environ 25 minutes de lecture · imprimable en PDF")}
${ch("Chapitre 1", "Définissez votre cible de stock", `<p>Un bon tri commence avant la recherche : sachez exactement ce que vous voulez rentrer.</p>${ul("eb-ok", ["<b>Modèles</b> : 3 à 5 références que vous revendez en moins de 30 jours", "<b>Fourchette de prix</b> : celle de votre clientèle, pas celle qui vous fait envie", "<b>Kilométrage et âge max</b>, adaptés à votre garantie et à votre atelier", "<b>Marge minimum</b> par voiture, en euros, frais compris", "<b>Rotation cible</b> : nombre de jours en stock au-delà duquel vous baissez le prix"])}<p>Écrivez-la. Chaque annonce qui sort de ce cadre est éliminée sans discussion.</p>`)}
${ch("Chapitre 2", "Filtrez le modèle et le moteur", `<p>Éliminez d'abord ce que vous ne reprendrez jamais : moteurs à risque, boîtes robotisées, versions société non signalées.</p>${MOTEURS}<p>Exception : même moteur avec l'historique complet et la preuve des travaux (courroie, chaîne, joint) peut entrer, avec une marge de sécurité plus haute.</p>`)}
${ch("Chapitre 3", "Paramétrez des recherches qui travaillent pour vous", `${ul("eb-ok", ["Une alerte par modèle et motorisation, pas une alerte large « citadine »", "Filtres : particuliers, prix max = votre plafond + 10 % (les vendeurs négocient), kilométrage max", "Rayon large autour de vos zones d'achat, et comparez avec le marché de votre zone de revente", "Plusieurs plateformes : Leboncoin, La Centrale, Facebook Marketplace, ParuVendu"])}<p>La vitesse compte : une annonce sous le marché part souvent en quelques heures. Utopicar analyse chaque nouvelle annonce dès qu'elle sort.</p>`)}
${ch("Chapitre 4", "Lisez le texte comme un vendeur l'écrit", `<p>Les formules qui cachent souvent un vrai problème :</p>${ul("eb-no", ["« Petit bruit, rien de grave »", "« Voyant allumé, sûrement un capteur »", "« Vendu en l'état, prix en conséquence »", "« Prévoir distribution », « clim à recharger », « passe le CT sans souci »", "« Cause double emploi » sur une voiture récente à très bas prix"])}<p>Attention aux négations : « joint de culasse refait », « non gagé », « pneus neufs », « aucun frais à prévoir » sont des points positifs. Un bon tri ne les élimine pas.</p>`)}
${ch("Chapitre 5", "Lisez les photos", `${ul("eb-ok", ["<b>Tableau de bord allumé</b> : voyants, kilométrage lisible, cohérent avec l'annonce", "<b>Photos de profil</b> : alignement des panneaux, différences de teinte, bas de caisse", "<b>Pneus</b> : marques différentes sur un même essieu, usure", "<b>Intérieur</b> : usure du volant et du siège par rapport au kilométrage", "<b>Photos absentes</b> : pas de photo d'un côté ou du tableau de bord, c'est rarement un oubli"])}<p>Des photos mauvaises sur une voiture saine, c'est au contraire une opportunité : moins de concurrence, et une revalorisation facile.</p>`)}
${ch("Chapitre 6", "Séparez les leviers des pièges", `<p><b>Leviers</b> (vous les chiffrez et vous les retirez du prix) : pneus, freins, batterie, vidange, rayures, pare-brise, amortisseurs, optiques.</p><p><b>Lourds</b> (chiffrables avec un diagnostic, sinon scénario haut) : boîte, embrayage, turbo, injecteurs, EGR, FAP, distribution.</p><p><b>Pièges</b> (vous partez) : joint de culasse, surchauffe, moteur HS, compteur incohérent, papiers manquants ou gage.</p>${PANNES}`)}
${ch("Chapitre 7", "Comparez au vrai marché, pas au prix affiché", `<p>Un prix n'est fiable qu'à partir d'un échantillon suffisant : même modèle et motorisation, année à ± 1 an, kilométrage à ± 30 000 km, sans épaves ni doublons.</p><p>Écarts mesurés sur 189 annonces de Clio IV diesel (2015, 140 000 km, prix attendu 7 000 € en dCi 90) :</p>${CLIO}<p>Une affaire, c'est un <b>prix réel (prix + travaux) au moins 5 % sous la cote</b>, sans piège et avec un moteur fiable.</p>`)}
${ch("Chapitre 8", "Appelez avec votre prix déjà calculé", `<p class="eb-formula">Revente − travaux − frais − marge = <b>plafond</b></p>${calc([["Revente à la cote", "6 950 €"], ["Travaux chiffrés", "− 800 €", "m"], ["Frais fixes et trajet", "− 400 €", "m"], ["Marge voulue", "− 800 €", "m"]], ["Plafond", "4 950 €"])}<p>Première offre environ 6 % sous le plafond, arrondie : <b>4 650 €</b>. Vous avez de la marge pour discuter sans dépasser votre limite.</p>`)}
${ch("Chapitre 9", "L'appel de qualification", `${sc("Ouverture", `Bonjour, je vous appelle pour votre [modèle]. Je suis professionnel de l'automobile, je peux me déplacer rapidement et payer par virement le jour même. J'ai quelques questions avant de venir.`)}${ol(["Depuis quand l'avez-vous, et pourquoi la vendez-vous ?", "Entretien : factures, distribution faite à quel kilométrage ?", "CT : date, défauts relevés, contre-visite ?", "Voyant, bruit, fuite, quelque chose à prévoir ?", "Pouvez-vous m'envoyer le rapport HistoVec et une photo du tableau de bord moteur allumé ?"])}<p>Notez les réponses. Une incohérence entre l'appel, l'annonce et HistoVec vaut un refus.</p>`)}
${ch("Chapitre 10", "La négociation sur place", `<p>Ne négociez qu'après l'inspection, avec la liste des défauts sous les yeux.</p>${sc("Offre chiffrée", `Elle est saine, mais il y a les pneus avant, les disques et un défaut au CT à reprendre, soit environ 800 € de remise en état. Je peux vous faire 4 650 €, virement immédiat, et je m'occupe des démarches.`)}${sc("Relance à J+5", `Bonjour, je reviens vers vous pour la [modèle]. Si elle est toujours disponible, mon offre tient toujours, et je peux passer cette semaine.`)}<p>Votre argument principal auprès d'un particulier : <b>la simplicité</b>. Paiement immédiat, pas de visites, pas de curieux, pas de risque de litige après la vente.</p>`)}
${ch("Chapitre 11", "Les papiers de l'achat professionnel", `${ul("eb-ok", ["Carte grise barrée et signée, certificat de cession, code de cession", "Certificat de situation administrative de moins de 15 jours", "Déclaration d'achat dans le SIV sous 15 jours (habilitation nécessaire)", "Inscription au registre de police, avec la pièce d'identité du vendeur", "Le CT n'est pas obligatoire quand l'acheteur est un professionnel de l'automobile, mais demandez-le : il vous sert pour chiffrer"])}<p class="eb-small">TVA : une voiture achetée à un particulier relève en général du régime de la TVA sur la marge. Voyez avec votre comptable.</p>`)}
${ch("Chapitre 12", "Suivez votre stock comme un tableau de bord", `${ul("eb-ok", ["<b>Jours en stock</b> par voiture : au-delà de votre seuil, baissez le prix par paliers de 3 %", "<b>Marge nette réelle</b> par voiture, comparée à la marge prévue au moment de l'achat", "<b>Taux de transformation</b> : annonces analysées → appels → visites → achats", "<b>Écart d'estimation</b> : prix de revente réel − cote estimée, pour affiner vos achats"])}<p>Au bout de 10 voitures, vous savez sur quels modèles et quelles zones vous gagnez vraiment de l'argent.</p>`)}
${ch("Annexe", "Les 17 citadines fiables entre 3 000 et 7 000 €", tableCitadines())}
<footer class="eb-end"><h4>L'outil fait ce tri pour vous</h4><p>Utopicar applique ces étapes à chaque annonce : cote sur un vrai échantillon, défauts repérés dans le texte, prix plafond calculé. Je vous écris pour ouvrir votre accès pendant la phase test.</p></footer></div>`;
}

// ================================================================== 3. Garagistes (vous)
function guideReprise(prenom: string) {
  return `<div class="eb">${cover("Guide garagistes", "Estimer une reprise en 2 minutes", `${prenom}, voici la méthode complète pour répondre à « elle vaut combien ma voiture ? » avec un prix juste, des chiffres que le client comprend, et une reprise qui ne vous coûte pas d'argent.`, "10 chapitres · environ 20 minutes de lecture · imprimable en PDF")}
${ch("Chapitre 1", "Le calcul d'une reprise", `<p class="eb-formula">Prix de revente − remise en état − frais − marge − risque = <b>prix de reprise</b></p>${calc([["Revente à la cote", "8 200 €"], ["Remise en état chiffrée", "− 650 €", "m"], ["Préparation, CT, garantie", "− 400 €", "m"], ["Marge voulue", "− 900 €", "m"], ["Risque (historique incomplet)", "− 250 €", "m"]], ["Reprise proposée", "6 000 €"])}<p>La ligne « risque » est ce qui vous protège : elle baisse quand le client apporte des factures et un HistoVec propre.</p>`)}
${ch("Chapitre 2", "Comparez ce qui est comparable", `${ul("eb-ok", ["Même modèle, même motorisation", "Année à ± 1 an, kilométrage à ± 30 000 km", "Même type de vendeur (particulier ou pro)", "Retirez épaves, voitures pour pièces, doublons postés dans plusieurs villes"])}<p>Avec 5 annonces vous avez un avis, avec 100 vous avez un prix. Sous 100 annonces exploitables, restez prudent sur votre chiffre.</p>`)}
${ch("Chapitre 3", "Appliquez les écarts qui comptent vraiment", `<p>Mesurés sur 189 annonces de Clio IV diesel :</p>${CLIO}<p>Couleur, options et finition ont moins d'effet qu'on le pense. L'historique d'entretien et l'état des pneus en ont plus.</p>`)}
${ch("Chapitre 4", "L'inspection de reprise en 15 points", `${ol(["Kilométrage au tableau de bord et voyants au contact", "Codes défauts à la valise, y compris effacés récemment", "Niveau et état de l'huile, du liquide de refroidissement", "Démarrage à froid, bruits de distribution", "Fuites sous le moteur et la boîte", "Embrayage : point de patinage", "Boîte : passage des rapports, bruits", "Freins : disques, plaquettes, frein à main", "Pneus : profondeur, marques, usure irrégulière", "Train avant : jeux, bruits en braquant", "Carrosserie : écarts, teintes, retouches, traces de choc", "Pare-brise, optiques, rétroviseurs", "Intérieur : usure, odeurs, humidité", "Clim, vitres, électronique", "Carnet, factures, doubles des clés"])}`)}
${ch("Chapitre 5", "Chiffrez la remise en état", `${PANNES}<p>Ajoutez la préparation VO : nettoyage complet, rénovation des optiques, retouches, vidange. Sur une citadine, comptez 150 à 400 € avant la mise en vente.</p>`)}
${ch("Chapitre 6", "Vérifiez le compteur et l'historique", `${ul("eb-ok", ["Kilométrages des CT sur HistoVec", "Factures d'entretien datées, carnet, étiquettes de vidange", "Données de la valise quand c'est possible"])}${ul("eb-no", ["Volant, pommeau, pédales très usés pour le kilométrage affiché", "Facture avec un kilométrage supérieur au compteur", "Sinistre déclaré ou procédure VE/VGE dans l'historique"])}<p>Au moindre doute, vous reprenez au prix d'un kilométrage inconnu, ou vous ne reprenez pas.</p>`)}
${ch("Chapitre 7", "L'administratif de la reprise", `${ul("eb-ok", ["Certificat de situation administrative de moins de 15 jours : pas de gage, pas d'opposition", "Carte grise au nom du client, barrée et signée, certificat de cession, code de cession", "Déclaration d'achat dans le SIV sous 15 jours", "Inscription au registre de police", "Si la voiture est en crédit ou en LOA : accord écrit de l'organisme, sinon pas de reprise"])}`)}
${ch("Chapitre 8", "Expliquez le prix au client", `<p>Montrez la cote pour son année et son kilométrage, puis chaque ligne qui fait baisser le prix.</p>${sc("Présentation", `Votre voiture se vend autour de 8 200 € sur le marché aujourd'hui. Pour la remettre en vente, il faut changer les pneus et les disques avant, et reprendre le défaut du CT, soit environ 650 €. Avec la préparation et la garantie, je peux vous la reprendre 6 000 €. Si vous me montrez les factures d'entretien, je peux remonter un peu.`)}<p>Le client accepte plus facilement un prix qu'il comprend ligne par ligne qu'un chiffre donné d'un bloc.</p>`)}
${ch("Chapitre 9", "Transformez le PV de CT en devis", `<p>Un PV de CT se traduit simplement : <b>mineure</b> = à prévoir, <b>majeure</b> = contre-visite sous 2 mois, <b>critique</b> = réparer avant de rouler, la voiture ne peut circuler que le jour du contrôle.</p><p>Transformez chaque ligne du PV en ligne de devis classée par urgence. Le client comprend ce qu'il doit faire, et les travaux restent chez vous, qu'il vous laisse sa voiture en reprise ou non.</p>`)}
${ch("Chapitre 10", "Reprise, dépôt-vente ou mandat", tab(["Formule", "Pour vous", "Pour le client"], [["Reprise", "Marge maximale, mais argent immobilisé et risque", "Simple et immédiat, prix plus bas"], ["Dépôt-vente", "Pas d'achat, commission à la vente, place occupée", "Meilleur prix, attente"], ["Mandat de vente", "Aucun stock, commission, annonce à votre nom", "Meilleur prix, il garde la voiture"]]) + `<p>Proposez le dépôt-vente ou le mandat quand la voiture est hors de votre cible de stock : vous gardez le client sans prendre le risque.</p>`)}
<footer class="eb-end"><h4>L'outil calcule cette cote pour vous</h4><p>Utopicar calcule la cote sur un vrai échantillon d'annonces et liste les écarts qui s'appliquent. Je vous écris pour ouvrir votre accès pendant la phase test.</p></footer></div>`;
}

// ================================================================== 4. Acheteurs particuliers (vous)
function guideParticulier(prenom: string) {
  return `<div class="eb">${cover("Guide acheteurs", "Acheter votre prochaine occasion sans vous faire avoir", `${prenom}, voici les vérifications à faire, dans l'ordre, pour acheter une voiture fiable au bon prix, et éviter les arnaques.`, "10 chapitres · environ 20 minutes de lecture · imprimable en PDF")}
${ch("Chapitre 1", "Votre vrai budget", `<p>Le prix de la voiture n'est pas le prix total. Prévoyez :</p>${calc([["Voiture", "6 000 €"], ["Carte grise (selon région et puissance)", "+ 150 à 400 €"], ["Assurance, premier mois", "+ 40 à 120 €"], ["Réserve pour l'entretien à venir", "+ 400 €"]], ["Budget total", "≈ 6 800 €"])}<p>Si votre budget total est de 6 000 €, cherchez une voiture autour de 5 200 €.</p>`)}
${ch("Chapitre 2", "Choisissez un modèle et un moteur fiables", `${tableCitadines()}${MOTEURS}<p class="eb-small">La réputation d'un moteur ne remplace pas l'examen de la voiture : l'historique d'entretien compte plus que le modèle.</p>`)}
${ch("Chapitre 3", "Repérez les arnaques dans les annonces", `${ul("eb-no", ["Prix 30 % sous le marché sans raison claire", "Vendeur « à l'étranger » ou « muté », voiture livrée par un transporteur", "Demande d'acompte pour « réserver » la voiture", "Photos reprises d'une autre annonce (faites une recherche d'image inversée)", "Pas de numéro de téléphone, uniquement des messages", "Plaque floutée et refus de donner l'immatriculation"])}`)}
${ch("Chapitre 4", "Posez ces 5 questions avant de vous déplacer", `${ol(["Depuis quand l'avez-vous, et pourquoi la vendez-vous ?", "Avez-vous les factures d'entretien ? La distribution a été faite à quel kilométrage ?", "Le CT a moins de 6 mois ? Il y a une contre-visite ?", "Un voyant allumé, un bruit, une fuite, quelque chose à prévoir ?", "Pouvez-vous m'envoyer le rapport HistoVec ?"])}`)}
${ch("Chapitre 5", "Vérifiez l'historique gratuitement", `<p>Le rapport <b>HistoVec</b> est gratuit, sur le site du gouvernement. Le vendeur le génère en 2 minutes et vous l'envoie. Vous y voyez :</p>${ul("eb-ok", ["Le nombre de propriétaires et depuis quand le vendeur l'a", "Les kilométrages relevés à chaque CT : ils doivent toujours augmenter", "Les sinistres importants déclarés", "La présence d'un gage ou d'une opposition"])}<p>Un vendeur qui refuse de l'envoyer : passez à l'annonce suivante.</p>`)}
${ch("Chapitre 6", "L'inspection avant l'essai", `${ul("eb-ok", ["Faites le tour à la lumière du jour : écarts entre les panneaux, différences de teinte", "Pneus : même usure des deux côtés, profondeur suffisante", "Intérieur : usure cohérente avec le kilométrage", "Sous le capot : niveau d'huile, pas de fuite, liquide de refroidissement propre", "VIN de la carte grise = VIN sur la voiture"])}`)}
${ch("Chapitre 7", "L'essai de 10 minutes", ESSAI.replace(/ tu as/g, " vous avez").replace(/Pose la main/g, "Posez la main").replace(/regarde sous/g, "regardez sous") + `<p>Au moindre doute, proposez un passage chez un garagiste avant l'achat (50 à 100 €). Si le vendeur refuse, vous avez votre réponse.</p>`)}
${ch("Chapitre 8", "Négociez avec des défauts chiffrés", `${PANNES}${sc("Votre offre", `La voiture me plaît. Il faudra changer les pneus avant et les plaquettes, soit environ 400 €. Je peux vous proposer [prix − 400 €], et on peut faire les papiers aujourd'hui.`)}<p>Chaque défaut vu pendant l'essai ou sur le PV de CT devient un argument chiffré, pas une impression.</p>`)}
${ch("Chapitre 9", "Papiers et paiement", `${PAPIERS.replace(/que tu as trouvé toi-même/, "que vous avez trouvé vous-même")}${ul("eb-no", ["Jamais d'argent avant d'avoir vu la voiture et les papiers", "Pas d'acompte par mandat cash, coupon ou crypto", "Chèque de banque : le vendeur appelle la banque émettrice avec un numéro trouvé lui-même", "Le plus simple : un virement instantané, fait ensemble au moment de la remise des clés"])}`)}
${ch("Chapitre 10", "Après l'achat", `${ul("eb-ok", ["<b>Assurez la voiture avant de rouler</b>, même pour la ramener chez vous", "Faites la carte grise à votre nom dans le mois, sur le site de l'ANTS, avec le code de cession", "Gardez le certificat de cession et le PV de CT", "Prévoyez une vidange si la dernière date de plus d'un an, et vérifiez la date de la distribution"])}`)}
<footer class="eb-end"><h4>Besoin d'un avis sur une annonce ?</h4><p>Utopicar calcule la vraie cote d'une annonce et repère les défauts dans le texte. Je vous écris pour vous ouvrir un accès pendant la phase test.</p></footer></div>`;
}

// ------------------------------------------------------------------ sélection

export type GuideId = "premiere-revente" | "trier-annonces" | "estimer-reprise" | "acheter-occasion";

export const GUIDES: { id: GuideId; titre: string; pour: string; resume: string; html: (prenom: string) => string }[] = [
  { id: "premiere-revente", titre: "Votre première revente, étape par étape", pour: "Se lancer dans l'achat-revente", resume: "16 chapitres, du cadre légal à votre plan sur 30 jours.", html: guideDebutant },
  { id: "trier-annonces", titre: "Trier 40 annonces en 10 minutes", pour: "Marchands et revendeurs", resume: "La méthode pour passer de 40 annonces à 3 appels utiles.", html: guideTri },
  { id: "estimer-reprise", titre: "Estimer une reprise en 2 minutes", pour: "Garagistes", resume: "Un prix juste, expliqué au client, sans perdre d'argent.", html: guideReprise },
  { id: "acheter-occasion", titre: "Acheter votre prochaine occasion sans vous faire avoir", pour: "Particuliers", resume: "Les vérifications à faire, dans l'ordre, jusqu'aux papiers.", html: guideParticulier },
];

/** Contenu d'un guide : complet, ou limité aux deux premiers chapitres (extrait gratuit). */
export function contenuGuide(id: GuideId, prenom: string, complet: boolean) {
  const g = GUIDES.find((x) => x.id === id) ?? GUIDES[0];
  const propre = prenom.replace(/[&<>"']/g, "").trim();
  // Sans prénom, « Prénom, ce guide… » devient « Ce guide… ».
  let html = g.html(propre || "\u0000").replace(/\u0000, (.)/, (_m, c: string) => c.toUpperCase());
  if (!complet) {
    const morceaux = html.split('<section class="eb-ch">');
    html = morceaux.slice(0, 3).join('<section class="eb-ch">') + "</div>";
  }
  // Titres décalés d'un niveau : la page porte déjà le h1.
  html = html.replace(/<(\/?)h3>/g, "<$1h2>").replace(/<(\/?)h4>/g, "<$1h3>");
  const chapitres = (html.match(/<section class="eb-ch">/g) ?? []).length;
  return { titre: g.titre, html, chapitres };
}
