"""Groupe A (2/2) : acheteurs particuliers. Deux séries : « le bon moteur par modèle » (liste fiable de l'outil,
fiabilite.ts) et « ce défaut te coûte combien » (fourchettes de defauts.ts et du guide du site). 32 carrousels."""
from common import *

def modele(slug, hook, nom, kicker, title, prendre, eviter, pourquoi, verif, caption, question, end):
    """Série « le bon moteur » : à prendre / à éviter / à vérifier, d'après la liste fiable de l'outil."""
    return car(slug, hook, caption, question, [
        S(kicker=kicker, title=title),
        S(title="À prendre", comp=[PILLS(*[[p, 'ok'] for p in prendre])], body=f"Sur la **{nom}**, les moteurs que l'outil classe fiables."),
        S(title="À éviter", comp=[PILLS(*[[p, 'bad'] for p in eviter])], body=pourquoi, relance="Image 4 : ce que tu vérifies quand même."),
        S(title="À vérifier", comp=[LIST(*verif)]),
    ], end)

def defaut(slug, hook, kicker, title, quote, lignes, tot, test, verdict, caption, question, end):
    """Série « ce défaut te coûte combien » : la phrase de l'annonce, le prix, le test sur place, le verdict."""
    return car(slug, hook, caption, question, [
        S(kicker=kicker, title=title),
        S(title="Dans l'annonce", comp=[QUOTE(quote)]),
        S(title="Le prix", comp=[TICKET(*lignes, tot=tot, totLab="À prévoir", tone='r')], relance="Image 4 : comment le repérer sur place."),
        S(title="Sur place", body=test, comp=[verdict]),
    ], end)

NEG = lambda t="Tu le déduis du prix, ou tu laisses.": VERDICT("À négocier", 'warn', t)
INSP = lambda t="Un garagiste avant de payer.": VERDICT("Faire inspecter", 'bad', t)

CARS = [
modele('clio-quel-moteur', 'FC', "Renault Clio III et IV", "Tu veux une Clio ?", "Le moteur\ncompte plus\nque la *version*.",
       ["1.2 16V 75 ch", "0.9 TCe 90", "1.5 dCi 75 / 90"], ["1.2 TCe 120", "Boîte EDC"],
       "Le 1.2 TCe 120 consomme de l'huile. La boîte EDC est réputée fragile.",
       ["Les factures, surtout sur le 1.5 dCi", "La distribution", "L'embrayage"],
       "Clio d'occasion : les moteurs fiables à prendre (1.2 16V, 0.9 TCe, 1.5 dCi) et ceux à éviter. Le moteur compte plus que la version.",
       "Tu as une Clio ? Quel moteur ?", "La bonne Clio,\n*le bon* moteur."),
modele('208-diesel-seulement', 'CC', "Peugeot 208", "Une 208 de 2012 à 2016 ?", "En essence,\nc'est un\n*PureTech*.",
       ["1.4 HDi 68", "1.6 HDi 92", "1.6 BlueHDi"], ["1.0 / 1.2 PureTech", "1.2 VTi 3 cylindres"],
       "Courroie de distribution dans l'huile, consommation d'huile : la facture arrive après l'achat.",
       ["La vanne EGR si elle roule en ville", "Les factures de distribution", "Le FAP sur le BlueHDi"],
       "Peugeot 208 d'occasion de 2012 à 2016 : prends-la en diesel. En essence, c'est un PureTech, avec sa courroie dans l'huile.",
       "Tu roules en 208 essence ?", "La 208,\n*en diesel*."),
modele('c3-ligne-moteur', 'FC', "Citroën C3 II", "Tu regardes une C3 ?", "Une bonne C3\nse joue sur\n*une* ligne.",
       ["1.1 / 1.4 essence", "1.4 HDi", "1.6 HDi / e-HDi"], ["1.2 PureTech", "Boîte ETG"],
       "Le PureTech et la boîte robotisée ETG font chuter la fiabilité.",
       ["La ligne « moteur » de l'annonce", "L'embrayage", "Les factures d'entretien"],
       "Citroën C3 II d'occasion : les moteurs à prendre (1.4 HDi, 1.6 HDi, essence 1.1 / 1.4) et le PureTech à éviter.",
       "Tu as quelle C3 ?", "Lis la ligne\n*moteur*."),
modele('fiesta-deux-pieges', 'EI', "Ford Fiesta VI", "Fiesta : un châssis réputé.", "Deux pièges\nque les acheteurs\n*ratent*.",
       ["1.25 / 1.4 essence", "1.4 / 1.6 TDCi"], ["1.0 EcoBoost", "Boîte Powershift"],
       "L'EcoBoost surchauffe, sa courroie baigne dans l'huile. La Powershift est fragile.",
       ["Le moteur exact sur la carte grise", "L'embrayage", "Les factures"],
       "Ford Fiesta VI d'occasion : un bon châssis, deux pièges. Évite le 1.0 EcoBoost et la boîte Powershift.",
       "Tu l'aurais vu, le piège ?", "Le bon châssis,\n*le bon* moteur."),
modele('yaris-increvable', 'RE', "Toyota Yaris II et III", "La Yaris essence", "passe les\n*190 000 km*.",
       ["1.0 VVT-i", "1.33 VVT-i", "Hybride 100 ch"], ["1.4 D-4D"],
       "Le diesel 1.4 D-4D a des injecteurs coûteux. Prends-la en essence ou en hybride.",
       ["Le carnet d'entretien", "L'embrayage", "La batterie hybride sur l'hybride"],
       "Toyota Yaris d'occasion : moteurs essence à chaîne quasi inusables et hybride 100 ch. Le diesel D-4D, à éviter.",
       "Tu as eu une Yaris ?", "La Yaris,\n*en essence*."),
modele('jazz-cvt', 'FC', "Honda Jazz II et III", "Honda Jazz :", "parmi les plus\nfiables. *Sauf* une\nboîte.",
       ["1.2 i-VTEC", "1.4 i-VTEC"], ["Boîte CVT premières séries"],
       "Les premières boîtes CVT sont fragiles. En boîte manuelle, la Jazz tient très longtemps.",
       ["Le type de boîte", "Le carnet d'entretien", "L'embrayage"],
       "Honda Jazz d'occasion : une des voitures les plus fiables. Les moteurs i-VTEC à prendre, la boîte CVT des premières séries à éviter.",
       "Tu connaissais la Jazz ?", "Fiable,\n*en manuelle*."),
modele('swift-rouille', 'FC', "Suzuki Swift", "Suzuki Swift :", "la mécanique tient.\nRegarde *dessous*.",
       ["1.2 essence", "1.3 essence"], ["Rouille avancée"],
       "Mécanique simple et solide, peu d'électronique. Le point faible est sous la caisse.",
       ["La rouille des passages de roue", "L'embrayage", "Le bas de caisse"],
       "Suzuki Swift d'occasion : mécanique simple et solide, entretien pas cher. Le point à vérifier, c'est la rouille.",
       "Tu regardes sous la voiture ?", "Regarde\n*dessous*."),
modele('mazda-2-amortisseurs', 'FC', "Mazda 2", "Mazda 2 :", "moteur fiable,\ndeux points\n*à voir*.",
       ["1.3 essence", "1.5 essence"], ["Rouille", "Amortisseurs fatigués"],
       "Moteurs atmosphériques fiables, souvent bien entretenus. Les soucis viennent de la caisse et des suspensions.",
       ["Bas de caisse et arches de roue", "Les amortisseurs", "Le carnet"],
       "Mazda 2 d'occasion : moteurs essence fiables. À vérifier : la rouille des bas de caisse et les amortisseurs.",
       "Tu connaissais ces deux points ?", "Le moteur, *oui*.\nLa caisse, vérifie."),
modele('aygo-c1-107', 'CV', "Toyota Aygo, Citroën C1 et Peugeot 107", "Aygo, C1, 107 :", "trois marques.\n*Une* seule\nvoiture.",
       ["1.0 VVT-i Toyota", "1.0 VTi 68 ch"], ["Boîte robotisée MMT / 2-Tronic"],
       "Le trio jumeau partage le même moteur Toyota. Évite seulement la boîte robotisée.",
       ["La boîte : manuelle de préférence", "L'embrayage", "L'entretien"],
       "Toyota Aygo, Citroën C1, Peugeot 107 : la même voiture, le même moteur Toyota. Choisis la moins chère des trois, en boîte manuelle.",
       "Tu savais que c'était la même ?", "Prends la *moins*\nchère des trois."),
modele('sandero-pas-chere', 'RE', "Dacia Sandero et Logan", "Dacia Sandero :", "pas chère\nà l'achat,\n*ni* à l'entretien.",
       ["1.2 16V", "1.6 MPI", "0.9 TCe 90", "1.5 dCi 75 / 90"], ["1.2 TCe 115 / 120"],
       "Mécanique Renault éprouvée. Le 1.2 TCe consomme de l'huile.",
       ["Les finitions et l'intérieur", "L'embrayage", "Les factures"],
       "Dacia Sandero d'occasion : mécanique Renault éprouvée, entretien bon marché. Les moteurs à prendre et le TCe à éviter.",
       "Sandero ou Clio, toi ?", "Simple,\n*solide*."),
modele('207-bons-moteurs', 'EI', "Peugeot 207 et 206+", "Peugeot 207 :", "très répandue.\nUn bon moteur\nsur *trois*.",
       ["1.4 essence 75 ch", "1.4 HDi 70", "1.6 HDi 90 / 92"], ["1.4 / 1.6 VTi", "1.6 THP"],
       "Les VTi et THP (moteur Prince) ont une chaîne de distribution fragile.",
       ["Le moteur exact", "La distribution", "Le carnet"],
       "Peugeot 207 d'occasion : très répandue, pièces bon marché. Uniquement avec les bons moteurs : 1.4 essence 75 ch ou HDi. Évite VTi et THP.",
       "Tu as eu une 207 ?", "La bonne 207,\n*le bon* moteur."),
modele('i20-rio-carnet', 'FC', "Hyundai i20 et Kia Rio", "Hyundai i20, Kia Rio :", "souvent un carnet\n*complet*.\nVoilà pourquoi.",
       ["1.2 essence", "1.25 essence", "1.4 essence"], ["Embrayage fatigué"],
       "Garantie longue d'origine : beaucoup ont été entretenues chez le concessionnaire. Le carnet le prouve.",
       ["Le carnet tamponné", "L'embrayage", "L'état intérieur"],
       "Hyundai i20 et Kia Rio d'occasion : fiables, bien équipées, souvent avec un carnet complet grâce à la garantie longue d'origine.",
       "Tu y avais pensé ?", "Le carnet,\n*une* preuve."),
modele('polo-tsi', 'FC', "Volkswagen Polo", "Volkswagen Polo :", "le *1.2 TSI*\ndépend de\nson année.",
       ["1.4 16V", "1.6 TDI", "1.2 TSI après 2013"], ["1.2 TSI avant 2013", "Boîte DSG7"],
       "Les premiers 1.2 TSI ont une chaîne de distribution fragile. La DSG7 aussi est à éviter.",
       ["L'année exacte du moteur", "La boîte", "Les factures"],
       "Volkswagen Polo d'occasion : le 1.2 TSI des premières années a une chaîne fragile. Après 2013, il est bien. Évite la DSG7.",
       "Tu savais pour l'année ?", "L'année *compte*."),
modele('twingo-quickshift', 'CC', "Renault Twingo II", "Renault Twingo II :", "petit prix. Une\nboîte à *fuir*.",
       ["1.2 16V 75 ch"], ["Boîte Quickshift"],
       "La boîte robotisée Quickshift coûte cher à réparer, parfois plus que la voiture.",
       ["Le type de boîte", "L'embrayage", "La rouille du hayon"],
       "Renault Twingo II d'occasion : petit prix, entretien très bon marché. À éviter : la boîte robotisée Quickshift.",
       "Ta Twingo, manuelle ou Quickshift ?", "La Twingo,\n*en manuelle*."),
modele('fabia-htp', 'FC', "Skoda Fabia II et III", "Skoda Fabia :", "fiable, sauf\nun petit moteur\n*3 cylindres*.",
       ["1.4 16V", "1.6 TDI", "1.2 TSI après 2013"], ["1.2 HTP 3 cylindres", "Boîte DSG"],
       "Le 1.2 HTP a une chaîne fragile. Sans preuve d'entretien, passe.",
       ["Le moteur exact", "Les factures de distribution", "La boîte"],
       "Skoda Fabia d'occasion : fiable avec les bons moteurs. Le 1.2 HTP 3 cylindres a une chaîne fragile.",
       "Tu connaissais le piège HTP ?", "La bonne Fabia,\n*le bon* moteur."),
modele('auris-hybride', 'RE', "Toyota Auris", "Toyota Auris :", "l'hybride qui\nfait ses *200 000 km*.",
       ["1.33 / 1.6 VVT-i", "Hybride 136 ch", "1.4 D-4D"], ["2.0 / 2.2 D-4D"],
       "Les gros diesels D-4D ont des soucis de joint de culasse.",
       ["Le carnet Toyota", "La batterie hybride", "L'embrayage (hors hybride)"],
       "Toyota Auris d'occasion : compacte fiable, l'hybride 136 ch dépasse souvent 200 000 km. Les gros diesels D-4D sont à éviter.",
       "Hybride ou diesel, toi ?", "L'Auris,\n*en hybride*."),

defaut('turbo-qui-siffle', 'CC', "Lu dans une annonce :", "« Léger\nsifflement. »\nLe *turbo* ?",
       "Bon état, ==léger sifflement à l'accélération==, rien de grave.",
       [["Turbo", "600 – 1 300 €"]], "jusqu'à 1 300 €",
       "Accélère franchement en 3e. Sifflement fort, manque de puissance, fumée à l'échappement : **le turbo fatigue**.", INSP(),
       "« Léger sifflement » dans une annonce de voiture d'occasion : le turbo, peut-être. 600 à 1 300 € de réparation.",
       "Tu as déjà entendu un turbo siffler ?", "Écoute *avant*\nd'acheter."),
defaut('injecteurs', 'CC', "Diesel d'occasion :", "un ralenti\nqui tremble\ncoûte *1 000 €*.",
       "Diesel, ==ralenti un peu instable==, démarre bien.",
       [["Injecteurs", "300 – 1 000 €"]], "jusqu'à 1 000 €",
       "Ralenti instable, démarrage difficile à chaud, fumée noire : **les injecteurs**.", INSP(),
       "Un diesel d'occasion au ralenti instable : les injecteurs, souvent. 300 à 1 000 € de réparation.",
       "Ton diesel tremble au ralenti ?", "Le ralenti\n*parle*."),
defaut('egr-fap', 'DO', "« Voyant moteur, rien de grave. »", "Sur un diesel,\nc'est souvent\nl'*EGR*.",
       "Diesel, ==voyant moteur allumé==, ==perte de puissance de temps en temps==.",
       [["Vanne EGR ou FAP", "150 – 900 €"]], "jusqu'à 900 €",
       "Perte de puissance, mode dégradé, voyant : **vanne EGR ou FAP encrassés**. Les petits trajets en ville les tuent.", INSP("Une valise de diagnostic avant de payer."),
       "Voyant moteur sur un diesel d'occasion : vanne EGR ou FAP encrassés, souvent. 150 à 900 € de réparation.",
       "Ton diesel roule surtout en ville ?", "Le voyant\na un *prix*."),
defaut('distribution-sans-facture', 'CC', "« Entretien à jour. »", "Sans facture,\nla distribution\nest *à faire*.",
       "Entretien à jour, ==distribution non précisée==, factures perdues.",
       [["Distribution + pompe à eau", "400 – 750 €"]], "jusqu'à 750 €",
       "Demande la **facture de distribution** : date et kilométrage. Pas de facture : compte-la à faire.", NEG("Si elle casse, c'est le moteur. Compte-la dans ton offre."),
       "« Entretien à jour » sans facture dans une annonce de voiture : la distribution est peut-être à faire. 350 à 750 €.",
       "Tu demandes la facture de distribution ?", "Pas de facture,\n*pas* de distribution."),
defaut('voyant-airbag', 'FC', "Voyant airbag allumé ?", "Le contrôle\ntechnique va\nle *voir*.",
       "Très bon état, ==petit voyant airbag==, ne gêne pas.",
       [["Voyant airbag", "100 – 400 €"]], "jusqu'à 400 €",
       "Démarre la voiture : le voyant airbag doit **s'éteindre** après quelques secondes. S'il reste, il faut un diagnostic.", NEG(),
       "Voyant airbag allumé sur une voiture d'occasion : 100 à 400 € de réparation, et un point qui compte pour ta sécurité.",
       "Tu as déjà eu ce voyant ?", "La sécurité\n*d'abord*."),
defaut('pare-brise-impact', 'FC', "Un impact sur le pare-brise ?", "Ton *assurance*\nle paie peut-être.",
       "Petit ==impact sur le pare-brise==, rien de grave.",
       [["Pare-brise", "60 – 450 €"]], "jusqu'à 450 €",
       "Un impact dans le champ de vision du conducteur se répare vite. **L'assurance bris de glace** le prend souvent en charge.", NEG("Vérifie ton contrat avant de négocier."),
       "Impact sur le pare-brise d'une voiture d'occasion : 60 à 450 €, souvent pris par l'assurance bris de glace.",
       "Tu as l'option bris de glace ?", "Vérifie ton\n*contrat*."),
defaut('amortisseurs', 'DM', "Pendant la visite,", "appuie sur\nun coin de\nla *voiture*.",
       "Bon état, ==tenue de route un peu molle==.",
       [["Amortisseurs avant", "250 – 500 €"]], "jusqu'à 500 €",
       "Appuie fort sur un coin et relâche. La voiture doit remonter **sans rebondir**. Elle rebondit : amortisseurs usés.", NEG(),
       "Tester les amortisseurs d'une voiture d'occasion en 5 secondes : appuie sur un coin. Amortisseurs usés : 250 à 500 €.",
       "Tu fais ce test ?", "5 secondes,\n*500 €*."),
defaut('bruit-roulement', 'DO', "Un bruit sourd en roulant ?", "Il grossit avec\nla *vitesse*.",
       "Bon état, ==petit bruit en roulant==, rien d'inquiétant.",
       [["Train avant ou roulement", "100 – 400 €"]], "jusqu'à 400 €",
       "Un bruit sourd qui monte avec la vitesse : **un roulement**. Des claquements en braquant : le train avant.", NEG(),
       "Bruit sourd en roulant sur une voiture d'occasion : roulement ou train avant, 100 à 400 €.",
       "Tu écoutes la voiture à l'essai ?", "Coupe la radio\n*à l'essai*."),
defaut('batterie-faible', 'FC', "Elle démarre lentement ?", "La batterie\na peut-être\n*6 ans*.",
       "Démarre bien, ==batterie à surveiller==.",
       [["Batterie", "90 – 160 €"]], "jusqu'à 160 €",
       "Regarde **la date** sur la batterie. Démarrage lent par temps froid : elle fatigue.", NEG(),
       "Batterie fatiguée sur une voiture d'occasion : 90 à 160 €. Regarde la date gravée dessus.",
       "Tu regardes la date de la batterie ?", "Lis la\n*date*."),
defaut('clim-souffle-chaud', 'DM', "Pendant l'essai,", "allume la clim.\n2 minutes, de\nl'air *froid* ?",
       "Clim ==à recharger==, sinon tout fonctionne.",
       [["Recharge ou réparation clim", "80 – 450 €"]], "jusqu'à 450 €",
       "Air froid en 2 minutes : OK. Air tiède : **recharge**, 80 €. Rien du tout : fuite ou compresseur, jusqu'à 450 €.", NEG(),
       "Clim d'une voiture d'occasion : recharge à 80 € ou réparation jusqu'à 450 €. Le test de 2 minutes à faire pendant l'essai.",
       "Ta clim souffle froid ?", "Teste *tout*."),
defaut('demarreur-alternateur', 'FC', "Démarrage laborieux ?", "Ce n'est pas\ntoujours la\n*batterie*.",
       "Démarre ==parfois difficilement==, sinon roule très bien.",
       [["Démarreur ou alternateur", "150 – 450 €"]], "jusqu'à 450 €",
       "Démarreur qui claque, **voyant batterie** allumé en roulant : démarreur ou alternateur.", NEG(),
       "Démarrage difficile sur une voiture d'occasion : démarreur ou alternateur, 150 à 450 €.",
       "Tu as déjà changé un démarreur ?", "Le bon\n*diagnostic*."),
defaut('echappement', 'DO', "Elle fait plus de bruit", "qu'une voiture\n*normale* ?",
       "Petit ==bruit d'échappement==, ne gêne pas.",
       [["Échappement", "100 – 350 €"]], "jusqu'à 350 €",
       "Bruit fort au ralenti, odeur de gaz : **l'échappement fuit**. Regarde sous la voiture, moteur tournant.", NEG(),
       "Échappement à reprendre sur une voiture d'occasion : 100 à 350 €. Le test à faire moteur tournant.",
       "Tu regardes sous la voiture ?", "Écoute\n*l'échappement*."),
defaut('rouille-dessous', 'FC', "Regarde dessous.", "La rouille\nne se voit pas\nsur les *photos*.",
       "Belle carrosserie, ==traces de rouille sous la voiture==.",
       [["Rouille à traiter", "100 – 600 €"]], "jusqu'à 600 €",
       "Bas de caisse, passages de roue, sous les portes. **Une lampe de téléphone suffit.**", NEG("Rouille perforante : tu pars."),
       "La rouille d'une voiture d'occasion ne se voit pas sur les photos. 100 à 600 € de traitement : où regarder.",
       "Tu regardes sous la voiture ?", "Une lampe,\n*dessous*."),
defaut('freins-vibrent', 'DM', "Au freinage,", "le volant\n*vibre* ?",
       "Freins ==à prévoir prochainement==.",
       [["Freins à refaire", "150 – 400 €"]], "jusqu'à 400 €",
       "Volant qui vibre au freinage : **disques voilés**. Bruit métallique : plaquettes à zéro.", NEG(),
       "Freins à refaire sur une voiture d'occasion : 150 à 400 €. Le test au freinage pendant l'essai.",
       "Tu freines fort pendant l'essai ?", "Freine\n*fort*."),
defaut('volant-moteur', 'CC', "Vibrations à l'embrayage ?", "Ce n'est peut-être\npas que\nl'*embrayage*.",
       "Diesel, ==vibrations au démarrage==, embrayage d'origine.",
       [["Volant moteur", "400 – 800 €"], ["Embrayage avec", "450 – 800 €"]], "jusqu'à 1 600 €",
       "Claquement au ralenti qui disparaît quand tu appuies sur l'embrayage : **volant moteur**.", INSP(),
       "Vibrations à l'embrayage sur un diesel d'occasion : le volant moteur, 400 à 800 €, souvent changé avec l'embrayage.",
       "Tu connaissais le volant moteur ?", "Un bruit,\n*deux* factures."),
defaut('leve-vitre', 'DM', "Pendant la visite,", "teste *toutes*\nles vitres.",
       "Tout fonctionne ==sauf vitre arrière gauche==.",
       [["Lève-vitre", "60 – 200 €"]], "jusqu'à 200 €",
       "Ouvre et ferme **chaque vitre**, les rétros, la fermeture centralisée. 2 minutes.", NEG(),
       "Lève-vitre en panne sur une voiture d'occasion : 60 à 200 €. Le test de 2 minutes à faire à chaque visite.",
       "Tu testes les vitres ?", "2 minutes,\n*200 €*."),
]
